### ISSUE TITLE
Is this still working?

### ISSUE THREAD

**Issue by MotherSoraka** [Hellisotherpeople/llm_steer-oobabooga#2]
i cant get it to work with any of L3, or Gemma 2 models. they all throw errors. tried both llamacpp_HF and llamacpp.

**Comment by MotherSoraka** [comment]
and why has no one ever talked about this?

**Comment by MotherSoraka** [comment]
nevermind. im dumb: "Note: This extension only works for models loaded using the "transformers" backend."

**Comment by Hellisotherpeople** [comment]
> and why has no one ever talked about this?

I think the LLM crowd has institutional blindness to the value of techniques which allow things similar to what's available here: https://github.com/ljleb/prompt-fusion-extension

I laugh when folks in the LLM world talk about Lora's like they're a new thing. The stable diffusion crowd had normalized Lora adapter usage/fine-tuning with Stable Diffusion back in 2022 and even today it's hard to find good Lora's for LLMs. Same dynamic.
